[package]
name = "sshfs-rs"
version = "0.1.0"
publish = false
authors = [ "Yusuke Sasaki <yusuke.sasaki.nuem@gmail.com>" ]
edition = "2018"

[dependencies]
anyhow = "1"
pico-args = "0.3"
polyfuse = "0.4"
ssh2 = "0.9"
whoami = "1"
